### ISSUE TITLE
Is it possible to use an IP or hostname other than localhost?

### ISSUE THREAD

**Issue by ssenaria** [darron/sifter#11]
I noticed Sifter is trying to connect to the loopback address. I could attach this node to the Consul cluster as a client but I would rather not. Is it possible to specify a remote IP?

**Comment by darron** [comment]
Hmm - that's the normal pattern for using Consul - using the local Consul agent. Any reason why you wouldn't add the node to the cluster?

It's not currently possible with the code - but would be a pretty quick addition.

**Comment by ssenaria** [comment]
Not a problem. I'm still fairly new to Consul. At first I was worried about the watches being fired every time, hence why I'm using Sifter. However, I realized you only set up watches on the nodes that you want. Not all servers/clients need to have the watches. We can close this.

**Comment by ssenaria** [comment]
I think the use case and maybe you can advise me on how to handle.

I have a cluster of 3 servers and another node acts as a client. I have the client respond to a non-loopback address so i can access the Consul UI. Hence, the scripts I'm running are on the client and I needed a way to interact with Consul but over the private IP (eg. 172.x.x.x)

**Comment by darron** [comment]
No worries - that's a perfectly reasonable use case - will work on adding this shortly.

**Comment by darron** [comment]
The above commit should take care of it - you can choose a different server by using this flag:

`-s, --server string   Consul server location (default "localhost:8500")`

It's set to localhost by default - so you don't have to use it if you're using it on the local Consul server.

That help?

**Comment by ssenaria** [comment]
Great, thanks a lot.
