### ISSUE TITLE
Does this work with other kinds of watches?

### ISSUE THREAD

**Issue by darron** [darron/sifter#5]

**Comment by darron** [comment]
It doesn't.

They have a different JSON structure that gets passed on STDIN - they are detailed here:

https://www.consul.io/docs/agent/watches.html

I think in order to do this properly - we should add some sort of `watchType` flag - and adjust the decodeStdin function to handle different JSON being passed to it. Then you'd start it with commands like these:

```
sifter --watch event -e chef-client
sifter --watch service -e 'consul-template -config -once'
sifter --watch keyprefix -e 'octo restart container'
```

**Comment by darron** [comment]
We're going to move ahead by creating new commands - have renamed the `run` command to `event` here:

https://github.com/darron/sifter/commit/0d452bce82f3fed6122a99e68a298aabfe88d92f

Starting on a `key` watch next.

**Comment by darron** [comment]
We now have a working `key` watch - to add to the working `event` watch. Working on the last two I care about:
1. Keyprefix.
2. Service.

**Comment by larssb** [comment]
Is this coming? :-)

**Comment by darron** [comment]
Yeah - not likely. I ended up not working on Consul after 2016.

**Comment by larssb** [comment]
Hi @darron,

Fair enough. All good. May I politely ask why you dumped Consul? Thank you and stay safe.

**Comment by darron** [comment]
I didn’t dump Consul as much as my next job didn’t use it at all. I still
think it’s an amazing tool.

My old job was still using Consul when I last talked to them in July.
